version = 0.1
[default.deploy.parameters]
stack_name = "frankle-highscores-service"
resolve_s3 = true
s3_prefix = "frankle-highscores-service"
region = "us-east-1"
confirm_changeset = false
capabilities = "CAPABILITY_IAM"
image_repositories = []
